"""
Django settings for ecommerce_api project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# pip install python-dotenv 
# pip3 install python-dotenv
from dotenv import load_dotenv, find_dotenv
import os

# USE ENVIRONMENT VARIABLES
load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

# If gunicorn is installed (only works on Unix systems), run 
# "python3 manage.py collectstatic" (to serves static files, which are used for Django Admin for example)
# and "gunicorn ecommerce_api.wsgi" to start gunicorn.
# Else, run "python3 manage.py runserver"
# (To test locally with DEBUG = False run: python3 manage.py runserver --insecure)

# To start ecommerce_api project with gunicorn and uvicorn:
# python -m gunicorn ecommerce_api.asgi:application -k uvicorn_worker.UvicornWorker

DEBUG = False

# IF DEBUG = False, we must add the allowed hosts (here we add localhost or 127.0.0.1 to run this server locally, on personal computer):
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # the new added apps:
    'corsheaders', 
    'rest_framework', 
    'authentication', 
    'orders', 
    'products', 
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware', # add CorsMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# CORS Settings

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:4173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:4173",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:4173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:4173",
]

# COOKIE SETTINGS
# CSRF_COOKIE_SAMESITE = 'Strict'
# SESSION_COOKIE_SAMESITE = 'Strict'
# CSRF_COOKIE_HTTPONLY = False  
# SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_AGE = 60 # 1 min
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True



# Use the custom user model and the custom EmailBackend
AUTH_USER_MODEL = 'authentication.CustomUser'
AUTHENTICATION_BACKENDS = ['authentication.backends.EmailOrUsernameBackend']

ROOT_URLCONF = "ecommerce_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], # TELL DJANGO WHERE THE TEMPLATES ARE
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ecommerce_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# change default django database to postgresql (this requires to install psycopg2: 
# pip3 install psycopg2 or pip3 install psycopg2-binary)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ["DATABASE_NAME"],
        'HOST': os.environ["DATABASE_HOST"],
        'USER': os.environ["DATABASE_USER"],
        'PASSWORD': os.environ["DATABASE_PASSWORD"],
        'PORT': os.environ["DATABASE_PORT"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"


# URL used to access the media
MEDIA_URL = '/media/'

# Actual directory user files go to
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# EMAIL SETTINGS

EMAIL_BACKEND = os.environ["EMAIL_BACKEND"] 
EMAIL_HOST = os.environ["EMAIL_HOST"] # Use your email provider's SMTP server
EMAIL_PORT = os.environ["EMAIL_PORT"]
EMAIL_USE_TLS = os.environ["EMAIL_USE_TLS"]
EMAIL_HOST_USER = os.environ["EMAIL_HOST_USER"]  # Your email
EMAIL_HOST_PASSWORD = os.environ["EMAIL_HOST_PASSWORD"]  # Your email password
EMAIL_FROM = os.environ["EMAIL_FROM"] 
PASSWORD_RESET_TIMEOUT = 14400 # PASSWORD_RESET_TIMOUT sts how long the link sent to an email will be valid. Here it is 14400 seconds = 4hours.