# Generated by Django 5.2.7 on 2025-12-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_image_product_cover_img_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sort_order',
        ),
    ]
